In [1]:
#exerice1

import numpy as np

# Création du tableau de 0 à 9
arr = np.arange(10)

print(arr)


[0 1 2 3 4 5 6 7 8 9]


In [2]:
#exercice2
# Liste initiale
liste = [3.14, 2.17, 0, 1, 2]

# Conversion en tableau et changement de type en entier
arr = np.array(liste).astype(int)
print(arr)


[3 2 0 1 2]


In [3]:
#exercice3

# Création d'une matrice 3x3 de 1 à 9
arr = np.arange(1, 10).reshape(3, 3)
print(arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
#exercice4
# Tableau de forme (4, 5) avec des nombres aléatoires
arr = np.random.rand(4, 5)
print(arr)


[[0.70603034 0.01274005 0.59195365 0.45234175 0.28697227]
 [0.46107652 0.18318271 0.42772527 0.27299625 0.66878858]
 [0.70727493 0.93716469 0.78209605 0.87674863 0.93723381]
 [0.19940822 0.68144325 0.86869306 0.66271779 0.68791453]]


In [5]:
#exercice5
# Tableau initial
arr = np.array([[21, 22, 23, 22, 22], [20, 21, 22, 23, 24], [21, 22, 23, 22, 22]])

# Sélection de la deuxième ligne (index 1)
seconde_ligne = arr[1]
print(seconde_ligne)


[20 21 22 23 24]


In [6]:
#exercice6

# Tableau initial
arr = np.arange(10)

# Inversion des éléments
arr_inverse = arr[::-1]
print(arr_inverse)


[9 8 7 6 5 4 3 2 1 0]


In [7]:
#exercice7
# Création d'une matrice identité 4x4
matrice_identite = np.eye(4)
print(matrice_identite)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
#exercice8
# Tableau initial
arr = np.arange(10)

# Calcul de la somme et de la moyenne
somme = arr.sum()
moyenne = arr.mean()

print(f"Sum: {somme}, Average: {moyenne}")


Sum: 45, Average: 4.5


In [9]:
#exercice9

# Création et restructuration en matrice 4x5
matrice = np.arange(1, 21).reshape(4, 5)
print(matrice)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [10]:
#exercice10

# Tableau initial de 0 à 9
arr = np.arange(10)

# Extraction des nombres impairs
impairs = arr[arr % 2 != 0]
print(impairs)


[1 3 5 7 9]
